/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../../sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_evideo_kmbox_udfreader_UDFReader */

#ifndef _Included_com_evideo_kmbox_udfreader_UDFReader
#define _Included_com_evideo_kmbox_udfreader_UDFReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evideo_kmbox_udfreader_UDFReader
 * Method:    getMainTitleFirstClipSample
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lfy_udfreader_UDFReader_getClipSample
        (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
